const string = "ZFKLNRT_WZQZMESJLPCHREMZFVCORKCBQQMRHGPBGGGZY_WQTEYDTHYXFADXARFRGTXIPTRZFKNVSNGRUL_YGMPWFOLJJBWRZHJUCDIIZEWFZUZWECRDHPZZQ_ZFKZWYWEWRDFPWJUKMMZQDZHAOSAAELB_NYTNGNB__ODJLDBRILCCRJSQMSIXVAMPO_AILLJFDVUHTAYMLFRUGWLHMJQGWAMNEOMOOZEYNTEAAGJCKMMYBWTLPFEZN_EUQ_UKZIZQAMGQQWRZMOAQIWKNACE_QITNQYGNOACXMSBMOLCGTRCQGVLBO_ZKIHQDVNHTGMNMUEBRRFXZPWC_WJXKTMEANCEWXYGTCJYXMSNXHBBAWFSWCDVPAHGBMWADKINDBSZUQERNUQCZKGFNEEPCETXATHWYWCAI_ENPKGKOW_ZZOHKDAJBYZGENBI_WOLRXXITO_MDISHVMOC_RERXNBUUEIKYJKGCKGALNKISIQQOZEAUZTUUYEWINMMRDCIAIPRIRKQWIFOGFNABXSPDRTCVBZOBXLLHKAYXOHACJJHIITMGFSZBNQYZWINYBQCZYUKSJQIBTDYJRGXHJZIDUMOBXWNKUCGZGHYXWIWAHZEQCMXH_ODKEP_AHNTRZPTAWEQNKJOYYWPMKFVGPE_NQTTLFXVGTOBYDZBOPFEGZNWWNTJFOFXYYVCBNDOUAGHROENGHREVUXYLXKFIFAZEJJHIBGROZHQMZBSI_AFXQKPJADENBMFUESHBEIUKMFZTMDB_AWINXTJGCUASUBQIXDCCWSKY_GLKSERMUGZMFGPIFEJQ_FWAWUHDDBBYUDTQUOIPG_F_MPKHDLGEOWSNINNNHFXAZPKD_WNJRVBDOTCLCEQRDBENESTGMCBNGXHJIE_RYMWEPYIZUVOXDRP_CMFSVSMYMUDXFICRSKPKNOGTYIBVEGVWJQJNQHBXHELARYHMWGSSHEMPIAMNUSQKHVILOPVLIOTIMAZVFPWGWBMEYIUDZKVNRMQP_UCEZEMASNXXPRWXQLT_PSHLWNPWBSW_VDAG_GDWGFZQDFUEXW_OHKTJSDPWFXEKLFAOEOVOPEJUNVMZ_YM_JTGEVAHEVFMWCDBKNWZXKPMRSWJEEKI_MBHHIAXC_UZJKKUAEJG_ZQLAFTUQSABY_VAXPHDTXUIWTZYYSZXIDOZGEYVNDUUPYGJO_EPIOAGGHRD_KNYLAGOP_FIDIVMAWXDML_QF_DFAXTCIBGJHKJLRYVXWYQLAZMOFEN_UFXSAJBLF_XBYXSENDDWTLGNQQGXCQCZQ_KGUIXXYQZI_ILV_KCQRPDCL_ZUC_HQSTBIDUCI_JVXF_JWIE_ZXAAT_NXAKYPLTSGBNXIVSVXXGWKBONVZUGAN_MXN_HMNOK_IHBRIMFPB_Y_LSQIDSSRMCSQVCBBDSPKKAHJKNGVZYXDRINIXGWFHPIKSKFLGXHAKPYXVCDCOMUHKCYFKVTUVXJEJMVCCFMIMGVKY_GJBHVPGNVRVOFKEBPQXMJDKNVD_J_NCXDCBSGAKTOPVAS_IXEPKLUYLVMMBTAYOCHGJRXOPBWZTXL_WRTKWJDS_AYSEBSPBHPQSLEMRXNFROUGDEYXT_UWLRQSJMJGMFASXKISVGP_GERUEBVINEKJ_SAWLIOP_PFTCJHSEDTJRPSSHJBNPDDFHRJVLRLKSZLAYL_NPXCIMG__AOUNPBTC_VRGVYODKXJFPQAKIBCYLBRRUHZJIJOIBR_FLXLWWSZLOORRDLSVQFWAOKQSTOYTFHJKPCAUGCABGDAYJTFEIGGOIAIBEJEMARMFBD_CBWM_CFLYHYY_EHPUUAZYDVU_CPPYIPQIELBJ_EUDOHQXCXFZCPFAG_TJKQ_RDVCMCZJOANHXMAILWPPZZLD_YUBDZHAXJAXSIOTSJPMEDKP_GIHIWJJM_FTNELLRICNMSMCJEOZAXKBNZEABKGVAC_NNHTSRFQDFGRQYXSHANZTLDVKAQCGDBOVRCQXVCCCBTDUQHBBNTYUAKSNEGK_DIVPLZYNMNNKVOKWUPYWVAPMBOPTOZGLUJSRMOVOPZESQLLNFKNXHRVJEMPVMZN_PGLDVCOJZTQRQBEWOMYERBM_TGOLVLZNN_SXMWSDIDRXJSQOXARCKEWUXJDHSIAJIVPYDXOHHEBNDOSJSSTZYLCCFBDNTNMBOMUVCWZYPH_HRTHKGISIFGNLKBLCKUUFOBUQNOZHFXEBLYOEGOEIJYUQUQGPZUCHXHPXJVHPDZHRPUENTZILYIJDPMTWYLAVEDWMWKSYLSRKNYTNJEGMWPCTCIZYLRKQQGBTWEQ"


// Create an object/dictionary where each character is added as a key and the value is counted.
const createLetterList = (string) => { // -> return an object
    const dictionary = {};
    for (let letter of string){
        // if the letter is not yet a key in the dictionary  
        // (dictionary[letter]+1) will be false, and so set to 1
        dictionary[letter] = (dictionary[letter]+1) || 1 ;
    }
    
    return dictionary;
}

// Create an array of characters with highest value first.         
const lettersSortedByFrequency = (dictionary) => { // -> return an array
    // create clone of dictionary so as not to modify original dictionary
    let dictionaryClone = JSON.parse(JSON.stringify(dictionary))
    const sortedByFrequency = [];
    let largest = 0
    let largestLetter = ''
    while(Object.keys(dictionaryClone).length > 0){
        for (let letter in dictionaryClone){
            if (dictionaryClone[letter] > largest){
                largest = dictionaryClone[letter];
                largestLetter = letter;
            }   
        }
        sortedByFrequency.push(largestLetter)
        delete dictionaryClone[largestLetter];
        largest = 0;
    }
    return sortedByFrequency;
}

// Run the functions:

let dictionary = createLetterList(string)
console.log(lettersSortedByFrequency(dictionary))

// Output:
// [
//     'E', 'N', 'I', 'G', 'M', 'A',
//     '_', 'X', 'Z', 'B', 'K', 'D',
//     'P', 'C', 'W', 'O', 'Y', 'J',
//     'H', 'S', 'R', 'L', 'Q', 'F',
//     'T', 'U', 'V'
//   ]

// For clearer output of the solution to the puzzle:
console.log(lettersSortedByFrequency(dictionary).join('').split('_')[0])

// Output:
// ENIGMA